export const LOGGING = {
    LOG_SUCCESSFUL: 'LOG_SUCCESSFUL'
}

export const ERROR = {
    ERROR_SHOWN: 'ERROR_SHOWN',
    ERROR_HIDDEN: 'ERROR_HIDDEN'
}

export const FETCHING = {
    IS_FETCHING: 'IS_FETCHING',
    IS_NOT_FETCHING: 'IS_NOT_FETCHING'
}

export const INPUT_VALUE = {
    LOGIN_CHANGE: 'LOGIN_CHANGE',
    PASSWORD_CHANGE: ' PASSWORD_CHANGE'
}
